- description: PCF Environment Configuration
  executionEnabled: true
  loglevel: INFO
  name: pcf-config-dev
  nodefilters:
    dispatch:
      excludePrecedence: true
      keepgoing: false
      rankOrder: ascending
      threadcount: 1
    filter: 'tags: pcf-dev'
  nodesSelectedByDefault: true
  options:
  - description: Set this value to '1' to update the scripts from source control.
    name: clean
  - description: The LDAP bind password if users are being sourced from LDAP. The LDAP url and bind user should be defined in config/config.yml.
    name: ldap-bind-password
    secure: true
    valueExposed: true
  - description: Ops Manager encryption key required if the Web GUI was restarted or VM was rebooted for initializing the authentication system.
    name: opsman-key
    secure: true
    valueExposed: true
  - description: The Ops Manager Web UI administrator password.
    name: opsman-password
    secure: true
    valueExposed: true
  scheduleEnabled: true
  sequence:
    commands:
    - script: |
        #!/bin/bash

        #
        # Rundeck variables
        #

        [ -z "@node.bitbucket@" ] && (
        	echo "ERROR! The Rundeck node environment variable \"bitbucket\" has not been set."
        	exit 1
        )
        [ -z "@node.opsman-host@" ] && (
        	echo "ERROR! The Rundeck node environment variable \"opsman-host\" has not been set."
        	exit 1
        )
        [ -z "@node.opsman-user@" ] && (
        	echo "ERROR! The Rundeck node environment variable \"opsman-user\" has not been set."
        	exit 1
        )
        [ -z "@option.opsman-password@" ] && (
        	echo "ERROR! The Ops Manager administration UI password needs to be provided."
        	exit 1
        )
        [ -z "@node.pcf-config@" ] && (
        	echo "ERROR! The Rundeck node environment variable \"pcf-config\" has not been set."
        	exit 1
        )

        export DOWNLOADS_DIR=$HOME/workspace/downloads
        export SCRIPTS_DIR=$HOME/workspace/scripts
        export BACKUP_DIR=$HOME/workspace/backups
        export CONFIG_DIR=$HOME/workspace/configs

        mkdir -p $DOWNLOADS_DIR
        mkdir -p $BACKUP_DIR

        if [ "@option.clean@" == "1" ]; then
            rm -fr $SCRIPTS_DIR
            rm -fr $DOWNLOADS_DIR
        fi
        if [[ ! -e $SCRIPTS_DIR ]]; then

            curl -v -s -k -L https://@node.bitbucket@/plugins/servlet/archive/projects/CLOUDF/repos/pcf-automation \
                -o $DOWNLOADS_DIR/pcf-automation.zip

            unzip  -o $DOWNLOADS_DIR/pcf-automation.zip -d $SCRIPTS_DIR
        fi

        curl -v -s -k -L https://@node.bitbucket@/plugins/servlet/archive/projects/CLOUDF/repos/@node.pcf-config@ \
            -o $DOWNLOADS_DIR/@node.pcf-config@.zip

        export OPSMAN_HOST="@node.opsman-host@"
        export OPSMAN_USER="@node.opsman-user@"
        export OPSMAN_PASSWD="@option.opsman-password@"
        export OPSMAN_KEY="option.opsman-key@"
        export PCF_CONFIG="@node.pcf-config@"
        export LDAP_BIND_PASSWD="@option.ldap-bind-password@"

        $SCRIPTS_DIR/run-pcf-config.sh

    keepgoing: false
    strategy: node-first
