---

default-shared-domains: [ 'cfapps-02.haas-40.pez.pivotal.io' ]
shared-domains: [ 'shared1.acme.com', 'shared2.acme.com' ]

default-security-groups:
    staging: [ 'all_open' ]
    running: [ 'all_open' ]

# Deletes any entities that are missing from source
# control and not in ignore lists if set to true
delete-missing-entities: true

ignore:
    security-groups: [ 'metrics-api' ]
    quotas: [ 'cloud-native-quota', 'p-spring-cloud-services', 'apigee-cf-service-broker-org-quota' ]
    orgs: [ 'system', 'p-spring-cloud-services', 'apigee-cf-service-broker-org', 'cloud-native' ]
    users: [ 'admin' ]
